
name: Fetch Stock Data

on:
  schedule:
    - cron: "15,30,45,0 3-9 * * 1-5"  # Every 15 minutes from 9:15 AM to 3:30 PM IST (Cron uses UTC)
  workflow_dispatch: # Manual trigger support

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch stock data
        run: python fetch_data.py

      - name: Commit and push data
        run: |
          git config --global user.name "your-username"
          git config --global user.email "your-email@example.com"
          git add database/stocks_data.db
          git commit -m "Update stock data"
          git push
